version: '2'

services:
  app:
    container_name: app
    restart: always
    build: .
    #command: "npm install"
    #command: "sleep 3600000"
    command: "ts-node ./src/index.ts"
    ports:
      - "9090:9090"
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /app/node_modules
  mongodb:
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
